### ISSUE TITLE
ISSN no registro da revista

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/core#531]
Entendo que um dos ISSNs é a chave para criação de páginas url, etc aqui no SciELO, mas o registro deve comportar todos os tipos de ISSNs que a revista tem ativos, que incluem.

1. ISSN Online 
2. ISSN Print
3. ISSN-L (esse não existe na title antiga, mas seria ótimo ter o campo)

Nos só excluímos do nosso registro title, os ISSNs que são oficialmente encerrados junto ao ISSN internacional pelos periódicos. Portanto, se a revista tem ISSN Print **ativo**, ele deve fazer parte do registro da revista e inclusive aparece na página da revista. [Exemplo](https://www.scielo.br/j/bcg/):

![image](https://github.com/scieloorg/core/assets/6084959/05ec086c-a052-4116-9967-048dffe0b2ce)

Note que na title original temos 3 campos de ISSN.

O ISSN chave na primeira página.
![image](https://github.com/scieloorg/core/assets/6084959/697bcf7c-291b-4bef-9fba-aeb1db857b05)

E a página com os campos ISSN impresso e online.
![image](https://github.com/scieloorg/core/assets/6084959/b9550817-496d-47ca-aa7a-0bddc9b35b21)

**Comment by robertatakenaka** [comment]
@RPostalli 
Eu acredito que a sua questão já está sendo atendida. Consute os dados de official journals (ou ISSN journals).

**Comment by RPostalli** [comment]
@robertatakenaka verdade, vou fechar este ticket. Tem até o L \o

**Comment by RPostalli** [comment]
Fechado
