### ISSUE TITLE
Verificar causa de erro de não registrar keyword sendo que o artigo possui keywords

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/core#631]
### Descrição da tarefa
https://core.scielo.org/admin/tracker/unexpectedevent/edit/b35ab331-f53a-4415-9198-092fcd82356f/

**Comment by samuelveigarangel** [comment]
Neste caso, o texto da keyword não está acompanhado de lang:
```json
{"keyword": {"lang": null, "text": "ômega-3"}
```

**Comment by robertatakenaka** [comment]
@samuelveigarangel o problema está no xml, no entanto, ele é antigo, resultado da primeira migração, não adianta pedir para corrigirem.
