### ISSUE TITLE
Revisar os templates das páginas informativas para adotar o design system https://ds.scielo.org

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/core#646]
### Descrição da tarefa
Revisar os templates das páginas informativas para adotar o design system https://ds.scielo.org
Os endereços de css, js e img do design system, devem ter o endereço para https://ds.scielo.org e não para os `static` da aplicação.
Corrigir os endereços e remover os arquivos estáticos.

Lugares para serem editados:

core/journalpage/templates/journalpage/base.html
```html
	08: <html class="no-js" lang="pt-BR"><script type="text/javascript" async="" src="{% static 'journal_about/js/recaptcha__pt_br.js' %}"></html>
	39: <link href="{% static 'images/favicons/favicon-16x16.png' %}" rel="shortcut icon" type="image/x-icon">
	40: <link href="{% static 'images/favicons/apple-touch-icon.png' %}" rel="apple-touch-icon">
	76: <script src="{% static 'js/jquery.js' %}"></script>
	77: <script src="{% static 'js/plugins.min.js' %}"></script>
	17: <link rel="icon" href="{% static 'journal_about/img/favicon.ico' %}">
	79: <script src="{% static 'journal_about/js/scielo-bundle-min.js' %}"></script>
```
core/core/templates/wagtailadmin/admin_base.html
```html
        14: <link href="{% static 'images/favicons/favicon-16x16.png' %}" rel="shortcut icon" type="image/x-icon">
        15: <link href="{% static 'images/favicons/apple-touch-icon.png' %}" rel="apple-touch-icon">
```
core/core/templates/wagtailadmin/base.html
```html
	27: <img src="{% static 'images/logos/logo_negative100x100.png' %}" alt="SciELO logo"/>
```
core/journalpage/templates/journalpage/about.html
```html
15-45:   <style>
	    ul.scielo__menu-contexto,
	    ul.scielo__menu-contexto ul{
	      list-style: none;
	    }
	    ul.scielo__menu-contexto ul{
	      margin-bottom: 1rem;
	    }
	    ul.scielo__menu-contexto .nav-link{
	      padding:0;
	      color: gray;
	    }
	    ul.scielo__menu-contexto .nav-link.active{
	      color:#3867ce;
	    }
	    .sticky-top{
	      top: 80px;
	    }

	    .bd-example h5,
	    .bd-example h4{
	      margin-top: 3rem;
	    }
	    .bd-example hr{
	      margin-top: 3rem;
	    }
	    .bd-example ul{
	      margin-bottom: 3rem;
	    }
	    a{
	      word-wrap: break-word;
	    }
	  </style>
```
core/journalpage/templates/journalpage/includes/footer.html
```html
26-45:
          <div class="col text-center mt-4 mb-4">
            <a href="http://www.fapesp.br/" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/FAPESP.png' %}" alt="FAPESP">
            </a>
            <a href="http://www.capes.gov.br/" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/CAPES.png' %}" alt="CAPES">
            </a>
            <a href="http://www.cnpq.br/" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/CNPq.png' %}" alt="CNPq">
            </a>
            <a href="http://bvsalud.org/" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/BVS.png' %}" alt="BVS">
            </a>
            <a href="http://regional.bvsalud.org/bvs/bireme/homepage.htm" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/BIREME.png' %}" alt="BIREME">
            </a>
            <a href="https://www.fapunifesp.edu.br/" target="_blank" class="mx-4 my-2 d-inline-block">
              <img src="{% static 'journal_about/images/FAP-UNIFESP.png' %}" alt="FAP-UNIFESP">
            </a>
          </div>
55:
	<img src="{% static 'journal_about/img/logo-open-access.svg' %}" alt="Open Access" class="logo-open-access">
```
core/journalpage/templates/journalpage/includes/header.html
```html
4-65:
	<style>
  body{
    padding-top: 115px;    
  }

  @media (min-width: 768px){ 
    body{
      padding-top: 74px; 
    }
  }
  header {
    background: #fff;
  }

  /*
  Ajustes para serem feitos no Design System:
  

  .scielo__menu{
    position: relative;
    margin-left: 8px;
  }
  
  .scielo__list-links{
    list-style: none;
    padding: 0;
    margin: 0;

  }
  .scielo__list-links a{
    display: block;
    white-space: nowrap;
  }
  */

  @media (min-width: 768px){
      
      .scielo__truncate{
        display: block;
        max-width: 285px;
      }

    }

  .journalContent .card{
    min-height: 220px;
  }
 
  .card {
    position: relative;
  }
  .card .card-body .btn{
    position: absolute;
    bottom: 16px;
  }
  /*
  strong.card-title{
    color: #333;
  }
  */

</style>
```
core/journalpage/templates/journalpage/includes/journal_info.html
```html
18:
	<img src="{% static 'journal_about/img/logo-open-access.svg' %}" alt="Open-access" class="logo-open-access" data-bs-toggle="tooltip" data-bs-original-title="by 4.0 ">
```

**Comment by ramoncordini** [comment]
@samuelveigarangel 

Arquivo:
core/journalpage/templates/journalpage/about.html

Remover css interno:

<style>
    ul.scielo__menu-contexto,
    ul.scielo__menu-contexto ul{
      list-style: none;
    }
    ul.scielo__menu-contexto ul{
      margin-bottom: 1rem;
    }
    ul.scielo__menu-contexto .nav-link{
      padding:0;
      color: gray;
    }
    ul.scielo__menu-contexto .nav-link.active{
      color:#3867ce;
    }
    .sticky-top{
      top: 80px;
    }

    .bd-example h5,
    .bd-example h4{
      margin-top: 3rem;
    }
    .bd-example hr{
      margin-top: 3rem;
    }
    .bd-example ul{
      margin-bottom: 3rem;
    }
    a{
      word-wrap: break-word;
    }
</style>

* Todo o código contido desde a tag <style> e </style> deve ser removido.
	Este CSS atualizado deve estar no design system previamente carregado em 
	https://ds.scielo.org/static/css/bootstrap.css

--

Arquivo:
core/journalpage/templates/journalpage/includes/footer.html

	journal_about/images/FAPESP.png
	https://ds.scielo.org/static/img/logo-footer-fapesp.svg

	journal_about/images/CAPES.png
	https://ds.scielo.org/static/img/logo-footer-capes.svg

	journal_about/images/CNPq.png
	https://ds.scielo.org/static/img/logo-footer-cnpq.svg

	journal_about/images/BVS.png
	https://ds.scielo.org/static/img/logo-footer-bvs.svg

	journal_about/images/BIREME.png
	https://ds.scielo.org/static/img/logo-footer-bireme.svg

	journal_about/images/FAP-UNIFESP.png
	https://ds.scielo.org/static/img/logo-footer-fap.svg

	journal_about/img/logo-open-access.svg
	https://ds.scielo.org/static/img/logo-open-access.svg

--

Arquivo:
core/journalpage/templates/journalpage/includes/header.html

Remover css interno:

	<style>
		body{
			padding-top: 115px;    
		}

		@media (min-width: 768px){ 
			body{
				padding-top: 74px; 
			}
		}
		header {
			background: #fff;
		}

		/*
		Ajustes para serem feitos no Design System:


		.scielo__menu{
			position: relative;
			margin-left: 8px;
		}

		.scielo__list-links{
			list-style: none;
			padding: 0;
			margin: 0;

		}
		.scielo__list-links a{
			display: block;
			white-space: nowrap;
		}
		*/

		@media (min-width: 768px){

		.scielo__truncate{
			display: block;
			max-width: 285px;
		}

		}

		.journalContent .card{
			min-height: 220px;
		}

		.card {
			position: relative;
		}
		.card .card-body .btn{
			position: absolute;
			bottom: 16px;
		}
		/*
			strong.card-title{
			color: #333;
		}
		*/

	</style>

	* Todo o código contido desde a tag <style> e </style> deve ser removido.
	Este CSS atualizado deve estar no design system previamente carregado em 
	https://ds.scielo.org/static/css/bootstrap.css

--

Arquivo:
core/journalpage/templates/journalpage/includes/journal_info.html

journal_about/img/logo-open-access.svg
https://ds.scielo.org/static/img/logo-open-access.svg
