### ISSUE TITLE
Artigos sem data de publicação no core.

### ISSUE THREAD

**Issue by gitnnolabs** [scieloorg/core#856]
### Descrição do problema

Durante a indexação dos dados no Solr para o índice do OAI, percebi que existe muitos artigos sem data de publicação porém verificando no https://kernel.scielo.br, existem vários casos que tem sim a data de publicação nas no core está sem a data.  

### Passos para reproduzir o problema

Para reproduzir o problema é possível acessar os artigos pelo kernel e verificar que existe data, exemplo: 

Artigo no core: https://core.scielo.org/admin/article/article/edit/507021/
Mesmo artigo no kernel: https://articlemeta.scielo.org/api/v1/article/?code=S0253-29482007000100001

Veja que no kernel existe a data de publicação: 

![Screenshot 2024-09-03 at 14 20 25](https://github.com/user-attachments/assets/f954a541-112c-42c1-a34e-63a6b0656c7a)

### Comportamento esperado

É esperado que os artigos que tenham data no kernel tenham data no core.

### Screenshots ou vídeos
N/A

### Anexos

Em anexo vou enviar uma lista de 159k de artigo que não está com data no índice para o OAI-PMH

[sem_source.id.zip](https://github.com/user-attachments/files/16852547/sem_source.id.zip)

### Ambiente utilizado
N/A

**Comment by samuelveigarangel** [comment]
Todos os artigos que consultei não apresentavam a data de publicação no site, ou seja, o elemento XML abaixo não estava presente:
Ex:
```xml
<pub-date date-type="pub">
<day>06</day>
<month>01</month>
<year>2000</year>
</pub-date>
```

Links para os artigos consultados:

[Artigo 1](https://core.scielo.org/media/pid_provider/1806/9681/pd/35/e017157918/QNk7Kv4WXc46yT8MQHqfNqq.xml)
[Artigo 2](https://core.scielo.org/media/pid_provider/1678/5150/pvb/36/11/1132/gcHrm6rrSbXzFvNjznRpQNK.xml)
[Artigo 3](https://core.scielo.org/media/pid_provider/1678/5150/pvb/37/10/1146/NRBgHJDydQzzZKFNtdhDLQB.xml)
[Artigo 4](https://core.scielo.org/media/pid_provider/1414/431X/bjmbr/51/06/e6555/ZmLjR3dBMC9ZXqWScJSZXWv.xml)
[Artigo 5](https://core.scielo.org/media/pid_provider/1806/9681/pd/35/e017161319/jFFyYZrWLYKTsbLMJtCqxNG.xml)
