### ISSUE TITLE
Adiciona o componente Search

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/core#90]
### Descrição da tarefa
- [ ] Adicionar / configurar a infraestrutura para o motor de busca

Basear-se em:
https://github.com/scieloorg/scms-oca/pull/21

**Comment by gitnnolabs** [comment]
@rg3915 segue um exemplo de como realizar essa atividade.

Esse PR adiciona o **search** no SCMS-OCA: https://github.com/scieloorg/scms-oca/pull/69
